# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jesho's Tech Journal
email: jeshocarmel@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
    I hope my journal helps you in your technical journey.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jeshocarmel.github.io" # the base hostname & protocol for your site, e.g. http://example.com
facebook_username: jeshocarmel
github_username:  jeshocarmel
#MEDIUM_USER_ID: 1ba67f8b1aefe9dc4196ce82a2138340fc86a2876212be7b2e0b48b6cbbbe89b1
#MEDIUM_INTEGRATION_TOKEN: 25db20ea847ceebb700026bb03bc925e9cdb830be8eeec9faf410d7a02440ed39

# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  #- jekyll-crosspost-to-medium

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
